"""initial_schema

Revision ID: cc0cbcff92ab
Revises:
Create Date: 2026-02-21 18:39:11.752056

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc0cbcff92ab"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("is_serviceable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
    )
    op.create_index(
        "ix_cities_is_serviceable", "cities", ["is_serviceable"], unique=False
    )
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=False)
    op.create_table(
        "packages",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column(
            "sample_types", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("base_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
    )
    op.create_index(op.f("ix_packages_code"), "packages", ["code"], unique=True)
    op.create_index("ix_packages_is_active", "packages", ["is_active"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "SUPER_ADMIN",
                "CITY_ADMIN",
                "CLIENT_USER",
                "PHLEBOTOMIST",
                name="user_role",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        "ix_users_is_active_role", "users", ["is_active", "role"], unique=False
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("old_value", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "clients",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("gst_number", sa.String(length=15), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("pincode", sa.String(length=6), nullable=True),
        sa.Column(
            "payment_terms",
            sa.Enum("PREPAID", "POSTPAID", "WALLET", name="payment_terms"),
            nullable=False,
        ),
        sa.Column("credit_limit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "rate_first_collection", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "rate_second_collection", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("rate_priority", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_clients_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("gst_number", name=op.f("uq_clients_gst_number")),
    )
    op.create_index("ix_clients_is_active", "clients", ["is_active"], unique=False)
    op.create_index(op.f("ix_clients_name"), "clients", ["name"], unique=False)
    op.create_table(
        "phlebotomists",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("id_proof_url", sa.String(length=500), nullable=True),
        sa.Column("certification_url", sa.String(length=500), nullable=True),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("bank_account_number", sa.String(length=30), nullable=True),
        sa.Column("bank_ifsc", sa.String(length=11), nullable=True),
        sa.Column("upi_id", sa.String(length=100), nullable=True),
        sa.Column("working_hours_start", sa.Time(), nullable=True),
        sa.Column("working_hours_end", sa.Time(), nullable=True),
        sa.Column("current_location_lat", sa.Float(), nullable=True),
        sa.Column("current_location_lng", sa.Float(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_phlebotomists_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phlebotomists")),
        sa.UniqueConstraint("user_id", name=op.f("uq_phlebotomists_user_id")),
    )
    op.create_index(
        op.f("ix_phlebotomists_employee_id"),
        "phlebotomists",
        ["employee_id"],
        unique=True,
    )
    op.create_index(
        "ix_phlebotomists_is_available", "phlebotomists", ["is_available"], unique=False
    )
    op.create_index(
        "ix_phlebotomists_location",
        "phlebotomists",
        ["is_available", "current_location_lat", "current_location_lng"],
        unique=False,
    )
    op.create_table(
        "zones",
        sa.Column("city_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_zones_city_id_cities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zones")),
        sa.UniqueConstraint("city_id", "name", name="uq_zones_city_id_name"),
    )
    op.create_index("ix_zones_is_active", "zones", ["is_active"], unique=False)
    op.create_table(
        "client_users",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_users_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_client_users_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_users")),
        sa.UniqueConstraint(
            "client_id", "user_id", name="uq_client_users_client_id_user_id"
        ),
    )
    op.create_table(
        "phlebotomist_cash_reconciliations",
        sa.Column("phlebotomist_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_appointments", sa.Integer(), nullable=False),
        sa.Column("cash_collected", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "online_collected", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("handed_over", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "discrepancy_amount", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "discrepancy_type",
            sa.Enum("SHORTAGE", "EXCESS", "NONE", name="discrepancy_type"),
            nullable=True,
        ),
        sa.Column("discrepancy_notes", sa.Text(), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["phlebotomist_id"],
            ["phlebotomists.id"],
            name=op.f(
                "fk_phlebotomist_cash_reconciliations_phlebotomist_id_phlebotomists"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
            name=op.f("fk_phlebotomist_cash_reconciliations_verified_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_phlebotomist_cash_reconciliations")
        ),
        sa.UniqueConstraint(
            "phlebotomist_id", "date", name="uq_cash_reconciliation_phlebotomist_date"
        ),
    )
    op.create_index(
        "ix_cash_reconciliation_phlebotomist_date",
        "phlebotomist_cash_reconciliations",
        ["phlebotomist_id", "date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_phlebotomist_cash_reconciliations_date"),
        "phlebotomist_cash_reconciliations",
        ["date"],
        unique=False,
    )
    op.create_table(
        "phlebotomist_zone_assignments",
        sa.Column("phlebotomist_id", sa.UUID(), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["phlebotomist_id"],
            ["phlebotomists.id"],
            name=op.f("fk_phlebotomist_zone_assignments_phlebotomist_id_phlebotomists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zones.id"],
            name=op.f("fk_phlebotomist_zone_assignments_zone_id_zones"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "phlebotomist_id", "zone_id", name=op.f("pk_phlebotomist_zone_assignments")
        ),
    )
    op.create_table(
        "pincodes",
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("pincode", sa.String(length=6), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zones.id"],
            name=op.f("fk_pincodes_zone_id_zones"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pincodes")),
    )
    op.create_index(op.f("ix_pincodes_pincode"), "pincodes", ["pincode"], unique=True)
    op.create_table(
        "localities",
        sa.Column("pincode_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pincode_id"],
            ["pincodes.id"],
            name=op.f("fk_localities_pincode_id_pincodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_localities")),
        sa.UniqueConstraint("pincode_id", "name", name="uq_localities_pincode_id_name"),
    )
    op.create_table(
        "orders",
        sa.Column("booking_id", sa.String(length=50), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("pincode_id", sa.UUID(), nullable=False),
        sa.Column("locality_id", sa.UUID(), nullable=True),
        sa.Column(
            "patient_title",
            sa.Enum("MR", "MRS", "MS", "DR", "MASTER", name="patient_title"),
            nullable=False,
        ),
        sa.Column("patient_name", sa.String(length=255), nullable=False),
        sa.Column("patient_age", sa.Integer(), nullable=False),
        sa.Column(
            "patient_gender",
            sa.Enum("MALE", "FEMALE", "OTHER", name="patient_gender"),
            nullable=False,
        ),
        sa.Column("patient_phone", sa.String(length=20), nullable=False),
        sa.Column("appointment_date", sa.Date(), nullable=False),
        sa.Column("appointment_time_slot", sa.String(length=50), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("landmark", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ASSIGNED",
                "ACCEPTED",
                "IN_TRANSIT",
                "COLLECTED",
                "UNCOLLECTED",
                "CANCELLED",
                "NSA",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Enum("NORMAL", "HIGH", name="order_priority"), nullable=False
        ),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "payment_mode",
            sa.Enum("CASH", "ONLINE", "PREPAID", name="payment_mode"),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum("PENDING", "COLLECTED", "VERIFIED", name="payment_status"),
            nullable=False,
        ),
        sa.Column("assigned_phlebotomist_id", sa.UUID(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collection_proof_url", sa.String(length=500), nullable=True),
        sa.Column("patient_signature_url", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_phlebotomist_id"],
            ["phlebotomists.id"],
            name=op.f("fk_orders_assigned_phlebotomist_id_phlebotomists"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_orders_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_orders_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["locality_id"],
            ["localities.id"],
            name=op.f("fk_orders_locality_id_localities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pincode_id"],
            ["pincodes.id"],
            name=op.f("fk_orders_pincode_id_pincodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(
        op.f("ix_orders_appointment_date"), "orders", ["appointment_date"], unique=False
    )
    op.create_index(
        op.f("ix_orders_assigned_phlebotomist_id"),
        "orders",
        ["assigned_phlebotomist_id"],
        unique=False,
    )
    op.create_index(op.f("ix_orders_booking_id"), "orders", ["booking_id"], unique=True)
    op.create_index(op.f("ix_orders_client_id"), "orders", ["client_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(
        "ix_orders_status_date", "orders", ["status", "appointment_date"], unique=False
    )
    op.create_table(
        "order_packages",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_packages_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_order_packages_package_id_packages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "order_id", "package_id", name=op.f("pk_order_packages")
        ),
    )
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("changed_by", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ASSIGNED",
                "ACCEPTED",
                "IN_TRANSIT",
                "COLLECTED",
                "UNCOLLECTED",
                "CANCELLED",
                "NSA",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_order_status_history_changed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_history_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_index(
        op.f("ix_order_status_history_created_at"),
        "order_status_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_status_history_order_id"),
        "order_status_history",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "sample_accessionings",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("vial_type", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "integrity",
            sa.Enum(
                "OK",
                "LIPEMIC",
                "LEAKED",
                "HEMOLYZED",
                "CLOTTED",
                "INSUFFICIENT",
                name="sample_integrity",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACCEPTED", "HOLD", "REJECTED", name="sample_status"),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("received_by", sa.UUID(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_sample_accessionings_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["received_by"],
            ["users.id"],
            name=op.f("fk_sample_accessionings_received_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sample_accessionings")),
    )
    op.create_index(
        op.f("ix_sample_accessionings_order_id"),
        "sample_accessionings",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sample_accessionings_status"),
        "sample_accessionings",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sample_accessionings_status"), table_name="sample_accessionings"
    )
    op.drop_index(
        op.f("ix_sample_accessionings_order_id"), table_name="sample_accessionings"
    )
    op.drop_table("sample_accessionings")
    op.drop_index(
        op.f("ix_order_status_history_order_id"), table_name="order_status_history"
    )
    op.drop_index(
        op.f("ix_order_status_history_created_at"), table_name="order_status_history"
    )
    op.drop_table("order_status_history")
    op.drop_table("order_packages")
    op.drop_index("ix_orders_status_date", table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_booking_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_assigned_phlebotomist_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_appointment_date"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("localities")
    op.drop_index(op.f("ix_pincodes_pincode"), table_name="pincodes")
    op.drop_table("pincodes")
    op.drop_table("phlebotomist_zone_assignments")
    op.drop_index(
        op.f("ix_phlebotomist_cash_reconciliations_date"),
        table_name="phlebotomist_cash_reconciliations",
    )
    op.drop_index(
        "ix_cash_reconciliation_phlebotomist_date",
        table_name="phlebotomist_cash_reconciliations",
    )
    op.drop_table("phlebotomist_cash_reconciliations")
    op.drop_table("client_users")
    op.drop_index("ix_zones_is_active", table_name="zones")
    op.drop_table("zones")
    op.drop_index("ix_phlebotomists_location", table_name="phlebotomists")
    op.drop_index("ix_phlebotomists_is_available", table_name="phlebotomists")
    op.drop_index(op.f("ix_phlebotomists_employee_id"), table_name="phlebotomists")
    op.drop_table("phlebotomists")
    op.drop_index(op.f("ix_clients_name"), table_name="clients")
    op.drop_index("ix_clients_is_active", table_name="clients")
    op.drop_table("clients")
    op.drop_index("ix_audit_logs_user_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index("ix_users_is_active_role", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_packages_is_active", table_name="packages")
    op.drop_index(op.f("ix_packages_code"), table_name="packages")
    op.drop_table("packages")
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_index("ix_cities_is_serviceable", table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
